name: C
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - name: host
      run: echo ${{  vars.HOST_TEST }}
      
    - name: cehis
      uses: appleboy/ssh-action@v0.1.10
      id: cc
      with:
        host:  ${{ secrets.HOST_TEST }}
        username: root
        password: qweASD@123
        script: cd /data/wwwroot/ceshi && git pull
        
    - name: 输出结果
      run: echo ${{ steps.cc.option.username }}
        
