name: Automatic deployment
run-name: ${{ github.actor }} is git push 
on:
  push:
    branches:
    - main
jobs:
  Pull:
    runs-on: ubuntu-latest
    steps:
    - name: ssh 
      uses: appleboy/ssh-action@v0.1.10
      id: ssh
      with:
        host:  ${{ secrets.HOST_TEST }}
        username: root
        password: qweASD@123
        script: cd /data/wwwroot/ceshi && git pull
        
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.qq.com
        server_port: 465
        username: 854377393@qq.com
        password:  ${{ secrets.TOKEN }}
        subject: Github Actions job result ${{ steps.ssh.outcome }}
        to: 854377393@qq.com
        from: 854377393@qq.com
        body: ${{ toJson( github ) }}
         
    

      
        
