name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - name: host
      run: echo ${{ secrets.HOST_TEST }} ${{ secrets.USER_NAME }} ${{ secrets.USER_PASSWORD }}
      
    - name: cehis
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST_TEST }}
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.USER_PASSWORD }}
        script: cd /data/wwwroot/ceshi && git pull
        
