iname: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - name: cehis
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.password }}
        run : git pull
