name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
    - name: cehis
      uses: appleboy/ssh-action@v0.1.10
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.password }}
        run: cd /data/wwwroot/ceshi && git pull
        
